server:
  port: 8080

spring:
  application:
    name: xunyou-backend
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.189.132:3306/db_xunyou
    username: root
    password: 123456



